### ISSUE TITLE
Refresh of Repository

### ISSUE THREAD

**Issue by algorys** [alexwenzel/dokuwiki-plugin-gitlog#1]
Hello,

I've install your plugin and very like it. But I've a problem, my repository is pull/push everyday so I was thinking that plugin refresh the commit all the day but it seems not. I've to edit and save multiple times to see the recent changes.

Have you a solution to refresh more frequently the page ?

**Comment by alexwenzel** [comment]
Hi,

You can read this article https://www.dokuwiki.org/caching and you can use this tag to prevent caching of this page:

```
~~NOCACHE~~
```

**Comment by algorys** [comment]
Ok, very nice. I forgot this tag. Thank you
